name: Build pyflood2022

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    strategy:
      max-parallel: 5
    
    continue-on-error: false

    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
     
      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH
      
      - name: Create conda environment 
        run: |
           source $CONDA/etc/profile.d/conda.sh
           conda env create -f env_pyflood2022.yml

      - name: Run scripts
        run: |
          source $CONDA/etc/profile.d/conda.sh
          conda activate env_pyflood2022
          cd $GITHUB_WORKSPACE
          for file in scripts/*.py; do
             echo Running $file
             python $file -v 6
          done  
        
      - name: Upload images
        uses: actions/upload-artifact@v4
        with:
          name: images
          path: images/*/*.png
 
      - name: Upload info
        uses: actions/upload-artifact@v4
        with:
          name: info
          path: images/*/*.json
 
